# Generated by Django 4.0.1 on 2022-02-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cientes',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
