# Generated by Django 4.0.1 on 2022-02-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_alter_cientes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cientes',
            name='direccion',
            field=models.CharField(max_length=50, verbose_name='la direccion'),
        ),
    ]
